services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: jinlin-rmq-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    restart: unless-stopped

  broker:
    image: apache/rocketmq:5.3.2
    container_name: jinlin-rmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      NAMESRV_ADDR: namesrv:9876
    depends_on:
      - namesrv
    command: sh mqbroker
    restart: unless-stopped
