-- 支付记录表
CREATE TABLE IF NOT EXISTS `payment_record` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `payment_no` VARCHAR(64) NOT NULL COMMENT '支付流水号',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单编号',
    `user_id` BIGINT(20) NOT NULL COMMENT '用户ID',
    `total_amount` DECIMAL(10, 2) NOT NULL COMMENT '订单总金额',
    `pay_amount` DECIMAL(10, 2) NOT NULL COMMENT '实付金额',
    `pay_type` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '支付类型：1-微信支付',
    `trade_type` VARCHAR(32) DEFAULT NULL COMMENT '交易类型：JSAPI、NATIVE、APP等',
    `transaction_id` VARCHAR(64) DEFAULT NULL COMMENT '微信支付订单号',
    `prepay_id` VARCHAR(64) DEFAULT NULL COMMENT '微信预支付ID',
    `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '支付状态：0-待支付，1-支付成功，2-支付失败，3-已退款，4-退款失败',
    `pay_time` DATETIME DEFAULT NULL COMMENT '支付成功时间',
    `refund_amount` DECIMAL(10, 2) DEFAULT NULL COMMENT '退款金额',
    `refund_status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '退款状态：0-未退款，1-退款中，2-退款成功，3-退款失败',
    `refund_time` DATETIME DEFAULT NULL COMMENT '退款时间',
    `refund_id` VARCHAR(64) DEFAULT NULL COMMENT '退款订单号',
    `reason` VARCHAR(255) DEFAULT NULL COMMENT '支付/退款原因',
    `notify_time` DATETIME DEFAULT NULL COMMENT '回调通知时间',
    `extend_info` TEXT DEFAULT NULL COMMENT '扩展信息(JSON格式)',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_no` (`payment_no`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_transaction_id` (`transaction_id`),
    KEY `idx_refund_id` (`refund_id`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付记录表';
